# Generated by Django 4.1 on 2024-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="管理员")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="年龄")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
            ],
        ),
    ]
